name: build_shell
description: Builds shell scripts that execute Dart snapshots (from build_vm_compilers).
version: 1.0.0
homepage: https://github.com/thosakwe/build_shell
author: Tobe O <thosakwe@gmail.com>
environment:
  sdk: '>=2.0.0-dev <3.0.0'
dependencies:
  build: ^1.0.0
  build_config: ^0.3.0
  build_vm_compilers: ^0.1.1
  path: ^1.0.0
  scratch_space: ^0.0.3
dev_dependencies:
  build_runner: ^1.0.0
